apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcpserver
  namespace: mcpserver
spec:
  selector:
    matchLabels:
      app: mcpserver
  replicas: 1
  template:
    metadata:
      labels:
        app: mcpserver
    spec:
      containers:
      - name: mcpserver
        image: registry.cn-hangzhou.aliyuncs.com/champly/mcpserver:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 20002
